// Code generated by MockGen. DO NOT EDIT.
// Source: ./gui/widgets.go

// Package gui is a generated GoMock package.
package gui

import (
	gomock "github.com/golang/mock/gomock"
	canvas "github.com/mum4k/termdash/private/canvas"
	terminalapi "github.com/mum4k/termdash/terminal/terminalapi"
	widgetapi "github.com/mum4k/termdash/widgetapi"
	gauge "github.com/mum4k/termdash/widgets/gauge"
	linechart "github.com/mum4k/termdash/widgets/linechart"
	text "github.com/mum4k/termdash/widgets/text"
)

// MockLineChart is a mock of LineChart interface.
type MockLineChart struct {
	ctrl     *gomock.Controller
	recorder *MockLineChartMockRecorder
}

// MockLineChartMockRecorder is the mock recorder for MockLineChart.
type MockLineChartMockRecorder struct {
	mock *MockLineChart
}

// NewMockLineChart creates a new mock instance.
func NewMockLineChart(ctrl *gomock.Controller) *MockLineChart {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineChart) EXPECT() *MockLineChartMockRecorder {
	_ = "STUB: not implemented"

	// Draw mocks base method.
	return nil
}

func (m *MockLineChart) Draw(cvs *canvas.Canvas, meta *widgetapi.Meta) error {
	_ = "STUB: not implemented"
	return nil
}

// Draw indicates an expected call of Draw.
func (mr *MockLineChartMockRecorder) Draw(cvs, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Keyboard mocks base method.
func (m *MockLineChart) Keyboard(k *terminalapi.Keyboard, meta *widgetapi.EventMeta) error {
	_ = "STUB: not implemented"
	return nil
}

// Keyboard indicates an expected call of Keyboard.
func (mr *MockLineChartMockRecorder) Keyboard(k, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Mouse mocks base method.
func (m_2 *MockLineChart) Mouse(m *terminalapi.Mouse, meta *widgetapi.EventMeta) error {
	_ = "STUB: not implemented"
	return nil
}

// Mouse indicates an expected call of Mouse.
func (mr *MockLineChartMockRecorder) Mouse(m, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Options mocks base method.
func (m *MockLineChart) Options() widgetapi.Options {
	_ = "STUB: not implemented"
	return *new(widgetapi.Options)
}

// Options indicates an expected call of Options.
func (mr *MockLineChartMockRecorder) Options() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Series mocks base method.
func (m *MockLineChart) Series(label string, values []float64, opts ...linechart.SeriesOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Series indicates an expected call of Series.
func (mr *MockLineChartMockRecorder) Series(label, values interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockText is a mock of Text interface.
type MockText struct {
	ctrl     *gomock.Controller
	recorder *MockTextMockRecorder
}

// MockTextMockRecorder is the mock recorder for MockText.
type MockTextMockRecorder struct {
	mock *MockText
}

// NewMockText creates a new mock instance.
func NewMockText(ctrl *gomock.Controller) *MockText { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockText) EXPECT() *MockTextMockRecorder {
	_ = "STUB: not implemented"

	// Draw mocks base method.
	return nil
}

func (m *MockText) Draw(cvs *canvas.Canvas, meta *widgetapi.Meta) error {
	_ = "STUB: not implemented"
	return nil
}

// Draw indicates an expected call of Draw.
func (mr *MockTextMockRecorder) Draw(cvs, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Keyboard mocks base method.
func (m *MockText) Keyboard(k *terminalapi.Keyboard, meta *widgetapi.EventMeta) error {
	_ = "STUB: not implemented"
	return nil
}

// Keyboard indicates an expected call of Keyboard.
func (mr *MockTextMockRecorder) Keyboard(k, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Mouse mocks base method.
func (m_2 *MockText) Mouse(m *terminalapi.Mouse, meta *widgetapi.EventMeta) error {
	_ = "STUB: not implemented"
	return nil
}

// Mouse indicates an expected call of Mouse.
func (mr *MockTextMockRecorder) Mouse(m, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Options mocks base method.
func (m *MockText) Options() widgetapi.Options {
	_ = "STUB: not implemented"
	return *new(widgetapi.Options)
}

// Options indicates an expected call of Options.
func (mr *MockTextMockRecorder) Options() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Write mocks base method.
func (m *MockText) Write(text string, wOpts ...text.WriteOption) error {
	_ = "STUB: not implemented"
	return nil
}

// Write indicates an expected call of Write.
func (mr *MockTextMockRecorder) Write(text interface{}, wOpts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockGauge is a mock of Gauge interface.
type MockGauge struct {
	ctrl     *gomock.Controller
	recorder *MockGaugeMockRecorder
}

// MockGaugeMockRecorder is the mock recorder for MockGauge.
type MockGaugeMockRecorder struct {
	mock *MockGauge
}

// NewMockGauge creates a new mock instance.
func NewMockGauge(ctrl *gomock.Controller) *MockGauge { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGauge) EXPECT() *MockGaugeMockRecorder {
	_ = "STUB: not implemented"

	// Draw mocks base method.
	return nil
}

func (m *MockGauge) Draw(cvs *canvas.Canvas, meta *widgetapi.Meta) error {
	_ = "STUB: not implemented"
	return nil
}

// Draw indicates an expected call of Draw.
func (mr *MockGaugeMockRecorder) Draw(cvs, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Keyboard mocks base method.
func (m *MockGauge) Keyboard(k *terminalapi.Keyboard, meta *widgetapi.EventMeta) error {
	_ = "STUB: not implemented"
	return nil
}

// Keyboard indicates an expected call of Keyboard.
func (mr *MockGaugeMockRecorder) Keyboard(k, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Mouse mocks base method.
func (m_2 *MockGauge) Mouse(m *terminalapi.Mouse, meta *widgetapi.EventMeta) error {
	_ = "STUB: not implemented"
	return nil
}

// Mouse indicates an expected call of Mouse.
func (mr *MockGaugeMockRecorder) Mouse(m, meta interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Options mocks base method.
func (m *MockGauge) Options() widgetapi.Options {
	_ = "STUB: not implemented"
	return *new(widgetapi.Options)
}

// Options indicates an expected call of Options.
func (mr *MockGaugeMockRecorder) Options() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Percent mocks base method.
func (m *MockGauge) Percent(p int, opts ...gauge.Option) error {
	_ = "STUB: not implemented"
	return nil
}

// Percent indicates an expected call of Percent.
func (mr *MockGaugeMockRecorder) Percent(p interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
